- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: 25
  when: inventory_hostname in groups['CentOS']
- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: 110
  when: inventory_hostname in groups['CentOS']
- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: 143
  when: inventory_hostname in groups['CentOS']

- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: 80
  when: inventory_hostname in groups['CentOS-b']
- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: 442
  when: inventory_hostname in groups['CentOS-b']

