- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: '{{ item }}'
    jump: ACCEPT
  become: yes
  when: inventory_hostname in groups['CentOS']
  with_items:
    - 25
    - 110
    - 143

- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: '{{ item }}'
    jump: ACCEPT
  become: yes
  when: inventory_hostname in groups['CentOS-b']
  with_items:
    - 80
    - 442
