---
- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: 21
    jump: ACCEPT
  become: yes
- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: 22
    jump: ACCEPT
  become: yes
- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: 53
    jump: ACCEPT
  become: yes
- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: 123
    jump: ACCEPT
  become: yes
- iptables:
    chain: INPUT
    protocol: UDP
    destination_port: 53
    jump: ACCEPT
  become: yes
