---
- iptables:
    chain: INPUT
    protocol: TCP
    destination_port: '{{ item }}'
    jump: ACCEPT
  become: yes
  with_items:
    - 21
    - 22
    - 53
    - 123
- iptables:
    chain: INPUT
    protocol: UDP
    destination_port: 53
    jump: ACCEPT
  become: yes
