---
- name: install mtr, tcpdump, nano
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - mtr
    - tcpdump
    - nano
- name: install NetworkManager-glib (CentOS machines)
  package:
    name: NetworkManager-glib
    state: latest
  tags: packages
  when: ansible_pkg_mgr == 'yum'
- name: install libnm-glib-dev, python-dbus (Debian machine)
  package:
    name: '{{ item }}'
    state: present
    update_cache: yes
  tags: packages
  when: ansible_pkg_mgr == 'apt'
  with_items:
    - libnm-glib-dev
    - python-dbus
