---
- name: install mtr
    package:
      name: mtr
      state: latest
- name: install tcpdump
    package:
      name: tcpdump
      state: latest
- name: install nano
    package:
      name: nano
      state: latest
- name: install cowsay
    package:
      name: cowsay
      state: latest

