---
- name: install mtr, tcpdump, nano
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - mtr
    - tcpdump
    - nano
- name: install NetworkManager-glib (CentOS machines)
  package:
    name: NetworkManager-glib
    state: latest
  tags: packages
  when: ansible_pkg_mgr == 'yum'
- name: install gir1.2-networkmanager-1.0 (Debian machine)
  package:
    name: gir1.2-networkmanager-1.0
    state: present
    update_cache: yes
  tags: packages
  when: ansible_pkg_mgr == 'apt'
