---
- hosts: all
  become: yes
  tasks:
    - user:
        name: manager
        group: wheel
  roles:
    - role: install_packages
    - role: transfer_keys
    - role: set_DNS
    - role: set_iptables
