---
- hosts: all
  become: yes
  vars:
    ansible_user: root
    ansible_ssh_pass: electric dancy pants
  roles:
    - role: create_user
    - role: install_packages
    - role: transfer_keys
    - role: set_DNS
