---
- hosts: all
  become: yes
  vars:
    ansible_user: manager
    ansible_become_user: root
    ansilbe_become_pass: electric dancy pants
  roles:
    - role: drop_protocols
    - role: set_universal_iptables
    - role: set_specified_iptables
